development:
  adapter: mysql2
  encoding: utf8
  host: localhost
  username: root
  password: root
  port: 3306
  database: boats_development

test:
  adapter: mysql2
  encoding: utf8
  host: localhost
  username: root
  password: root
  port: 3306
  database: boats_test